force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_Tracing__c/Location_Tracing__c.object-meta.xml
<CustomObject>
    <label>Location Tracing</label>
    <nameField>
        <displayFormat>LT-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Tracing</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_Tracing__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Visiting People</relationshipLabel>
    <relationshipName>Location_Tracing</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location_Tracing__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <label>Person</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Visited Locations</relationshipLabel>
    <relationshipName>Location_Tracing</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CTLocationTriggerHandler.cls
public with sharing class CTLocationTriggerHandler {
    
    
    public static void beforeInsert(List<Location__c> newRecords){
        for(Location__c location : newRecords){
            location.Status__c = 'Green';
        }
    }

    public static void beforeUpdate(List<Location__c> newRecords, Map<Id, Location__c> oldRecordsMap){
        for(Location__c location : newRecords){
            if(location.Status__c != oldRecordsMap.get(location.Id).Status__c){
                location.Status_Update_Date__c = Date.today();
            }
        }
    }

    public static void afterUpdate(List<Location__c> newRecords, Map<Id, Location__c> oldRecordsMap){
        Set<Id> redStatusLocationIds = new Set<Id>();
        for(Location__c location : newRecords){
            if(location.Status__c == 'Red' && oldRecordsMap.get(location.Id).Status__c != 'Red'){
                redStatusLocationIds.add(location.Id);
            }
        }
      Set<Id> personIds = new Set<Id>();
        List<Location_Tracing__c> locationTraces = CTLocationTracingController.getLocationsByLocationIds(redStatusLocationIds);
        for(Location_Tracing__c trace : locationTraces){
            personIds.add(trace.Person__c);
        }

        List<Person__c> personsToUpdate = new List<Person__c>();
        for(Id pid : personIds){
            personsToUpdate.add(new Person__c(Id = pid, Health_Status__c = 'Yellow'));
        }
        if(personsToUpdate.size() > 0){
            update personsToUpdate;
        }
        
    }
}