force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_Tracing__c/Location_Tracing__c.object-meta.xml
<CustomObject>
    <label>Location Tracing</label>
    <nameField>
        <displayFormat>LT-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Tracing</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_Tracing__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Visiting People</relationshipLabel>
    <relationshipName>Location_Tracing</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location_Tracing__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <label>Person</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Visited Locations</relationshipLabel>
    <relationshipName>Location_Tracing</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CTLocationTracingTriggerHandler.cls
public with sharing class CTLocationTracingTriggerHandler {
    

    public static void beforeInsert(List<Location_Tracing__c> newLocationTraces){
        List<Location_Tracing__c> duplicates = CTLocationTracingController.checkDuplicates(newLocationTraces);

        if(duplicates != null && duplicates.size()>0){
            for(Location_Tracing__c trace : newLocationTraces){
                trace.addError('Duplicate Record Found. Location : '+ trace.Location__c+' Perosn Id: '+ trace.Person__c);
            }
        }

    }
}